configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/ref.smk"
include: "rules/map.smk"

##### target rules #####


rule all:
    input:
        get_final_output(),
        "resources/index_genome",
