configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/qc_reads.smk"
include: "rules/ref.smk"
include: "rules/map.smk"
include: "rules/count.smk"
include: "rules/qc_samples.smk"

##### target rules #####


rule all:
    input:
        get_final_output(),
        "resources/index_genome",
